export const MSG = {
  // Host -> Router -> Engine
  CMD_START_SESSION: "CMD_START_SESSION",
  CMD_STOP_SESSION: "CMD_STOP_SESSION",
  CMD_PING_WIDGET: "CMD_PING_WIDGET",

  // Engine -> Router -> Host
  EVENT_STATE_CHANGE: "EVENT_STATE_CHANGE",
  EVENT_TRANSCRIPT: "EVENT_TRANSCRIPT",
  EVENT_ERROR: "EVENT_ERROR",
};
